# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bsdl < Formula
  desc "BeatStars Music Downloader"
  homepage "https://github.com/adithayyil/bsdl"
  version "0.3"

  on_macos do
    on_intel do
      url "https://github.com/adithayyil/bsdl/releases/download/v0.3/bsdl_Darwin_x86_64.tar.gz"
      sha256 "7c2ea1a6a7b3e1937e753db4fddf607cc79b3a01a1c8483e9fa6e02758af3a85"

      def install
        bin.install "bsdl"
      end
    end
    on_arm do
      url "https://github.com/adithayyil/bsdl/releases/download/v0.3/bsdl_Darwin_arm64.tar.gz"
      sha256 "bd74a8c56dfef715eed80522dcc46d1e0d9529a24d261ea81374c4260833e27d"

      def install
        bin.install "bsdl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adithayyil/bsdl/releases/download/v0.3/bsdl_Linux_x86_64.tar.gz"
        sha256 "50a29be69cb757c621ff1e0f894c2d6ebf7388534f8208467810d4a78caa6240"

        def install
          bin.install "bsdl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adithayyil/bsdl/releases/download/v0.3/bsdl_Linux_arm64.tar.gz"
        sha256 "3cfe645bb74eef6828336976519bc7d7aaf6670d9246c6f8c5fe3a0a3b95ac8a"

        def install
          bin.install "bsdl"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Usage: bsdl --help
    EOS
  end
end
