# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bsdl < Formula
  desc "BeatStars Music Downloader"
  homepage "https://github.com/adithayyil/bsdl"
  version "1.0"

  on_macos do
    on_intel do
      url "https://github.com/adithayyil/bsdl/releases/download/v1.0/bsdl_Darwin_x86_64.tar.gz"
      sha256 "3da2492057e1b4ae98418c0be72c4410876151d8641fcceec7265846c6ebee47"

      def install
        bin.install "bsdl"
      end
    end
    on_arm do
      url "https://github.com/adithayyil/bsdl/releases/download/v1.0/bsdl_Darwin_arm64.tar.gz"
      sha256 "519a86b0cf3a4c0c39247d63c1ac0952b6af5908084aee21924e79468458bae4"

      def install
        bin.install "bsdl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adithayyil/bsdl/releases/download/v1.0/bsdl_Linux_x86_64.tar.gz"
        sha256 "5569e9721d2e3ad19aa402c59e07846aabae2cb3bb3fcbc8b38f64be64091456"

        def install
          bin.install "bsdl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adithayyil/bsdl/releases/download/v1.0/bsdl_Linux_arm64.tar.gz"
        sha256 "7a0676532724b55127166e830b9129dce2ed24b4f09f3542ffd65eccdccdb6b5"

        def install
          bin.install "bsdl"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Usage: bsdl --help
    EOS
  end
end
